### ISSUE TITLE
ValueError: file does not contain alignment data

### ISSUE THREAD

**Issue by ccmeth** [ijuric/MAPS#45]
Dear MAPS team,

  Recently, I tried to use MAPS for tackling PLAC-seq data, however, an error appeared at the beginning of this process (the data I used is GM12878 provided there). Could you please tell me how to address this problem?

Wed Feb 23 16:17:32 2022 starting mapping and filtering operation
Wed Feb 23 16:17:32 2022 calling bwa for /home/bd/test_maps/SRR3467175_R1.fastq
Wed Feb 23 16:17:32 2022 calling bwa for /home/bd/test_maps/SRR3467175_R2.fastq
Traceback (most recent call last):
  File "/home/bd/MAPS-master/bin/feather/feather_pipe", line 125, in <module>
    main()
  File "/home/bd/MAPS-master/bin/feather/feather_pipe", line 53, in main
    filter_output_filename = filter_main(fastq1, fastq2, bwa_index, mapq, outdir, prefix, threads, optical, to_file = False)
  File "/home/bd/MAPS-master/bin/feather/feather_filter_chr.py", line 50, in filter_main
    bwa = pysam.AlignmentFile(bwa_filename)
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 947, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data

Hao

**Comment by garci1294** [comment]
@ccmeth were you able to find the solution for this issue?

Thanks,
Jesus

**Comment by j-andrews7** [comment]
For anyone who runs into this, it seems to stem from the FASTA file not being in the same location as an actual BWA index. You **must** have the other BWA index files in the same location.

Error message could be improved, @ijuric
